import { StyleSheet } from 'react-native';
import { SPACING } from '../constants/constants';

const Styles = StyleSheet.create({
	container: {
		flex: 4,
		justifyContent: 'space-evenly',
		alignItems: 'center',
	},
	box: {
		backgroundColor: '#000',
		flex: 3,
		width: '100%',
		alignItems: 'center',
	},
	box2: {
		width: '100%',
		flex: 1,
		alignItems: 'center',
		justifyContent: 'space-evenly',
		backgroundColor: 'black',
	},
	content: {
		flex: 3,
		color: 'white',
		backgroundColor: 'transparent',
		borderColor: 'darksalmon',
		borderWidth: 1,
		padding: 5,
		borderRadius: 5,
		fontSize: 14,
		justifyContent: 'center',
		alignContent: 'center',
		margin: 3,
	},
	box3: {
		flex: 1,
		width: '100%',
		flexDirection: 'row',
		padding: 10,
		alignItems: 'center',
		justifyContent: 'space-evenly',
		margin: 3,
	},
	btnContainer: {
		padding: 5,
	},
	goTotBtn: {
		color: 'white',
		backgroundColor: 'darkseagreen',
		padding: 10,
		borderRadius: 7,
		fontWeight: 'bold',
		textDecorationLine: 'underline',
	},
	newScanBtn: {
		color: 'white',
		backgroundColor: 'darksalmon',
		padding: 10,
		borderRadius: 7,
		fontWeight: 'bold',
		textDecorationLine: 'underline',
	},
	searchBar: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-around',
	},
	clearBtn: {
		borderColor: 'darkred',
		borderWidth: 1,
		borderRadius: SPACING,
		width: SPACING * 3.5,
		padding: 5,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#000',
	},
	clearText: { fontSize: 14, color: 'white' },
	searchInput: {
		margin: 5,
		alignSelf: 'center',
		justifyContent: 'center',
		borderColor: 'darkred',
		borderWidth: 2,
		borderRadius: SPACING / 2,
		height: SPACING * 2,
		width: 160,
		padding: SPACING / 2,
	},
	scrollViewCards: {
		flexDirection: 'row',
		padding: SPACING,
		marginTop: SPACING / 2,
		marginBottom: SPACING / 2,
		borderRadius: SPACING / 2,
		backgroundColor: 'rgba(255, 255, 255, .9)',
		shadowColor: '#000',
		shadowOffset: { width: 0, height: SPACING / 2 },
		shadowOpacity: 0.9,
		shadowRadius: SPACING,
	},
	deleteCardBtn: {
		borderColor: 'darkred',
		borderWidth: 1,
		borderRadius: SPACING,
		width: SPACING * 1.2,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		marginRight: 5,
		backgroundColor: 'black',
	},
	cardData: {
		fontSize: 14,
		color: '#000',
		borderColor: 'darkred',
	},
	searchBtn: {
		alignItems: 'center',
		justifyContent: 'center',
		borderColor: 'darkred',
		borderWidth: 2,
		borderRadius: SPACING / 2,
		height: SPACING * 2,
		width: SPACING * 2,
		padding: 2,
	},
});

export default Styles;
